import { useEffect, useState } from "react";
import type { Decorator, Meta, StoryObj } from "@storybook/react";

import Dialog from "./Dialog";
import { DialogBreakpoint, DialogState } from "./Dialog.types";
import PopoverFooter from "../Popover/PopoverFooter";
import Button from "../Button/Button";
import StepItemGroup from "../StepItemGroup/StepItemGroup";
import StepItem from "../StepItemGroup/StepItem";
import AlertBanner from "../AlertBanner/AlertBanner";
import { StepItemProgress } from "../StepItemGroup/StepItem.types";

type StoryArgs = {
  kind: "default" | "focus";
  breakpoint: DialogBreakpoint;
  error: boolean;
};

const noop = () => {};

// The Dialog now supplies the content-slot padding (24/16) + gap; the demo
// content just fills it.
const SampleBody = () => (
  <div style={{ display: "flex", flexDirection: "column", gap: "var(--size-3)" }}>
    <p style={{ margin: 0, font: "var(--font-body-400-compact)", color: "var(--text-subtle)" }}>
      Dialog is a modal built on Popover. A default dialog is a card (desktop) or drawer (mobile); a focus dialog is a
      near/full-screen multi-step flow.
    </p>
    {Array.from({ length: 5 }).map((_, i) => (
      <div key={i} style={{ height: 44, borderRadius: "var(--border-radius-1_5)", background: "var(--gray-a3)" }} />
    ))}
  </div>
);

const errorBanner = (
  <AlertBanner type="banner" status="error" ctaLabel="Retry" ctaOnClick={noop}>
    Something went wrong. Please try again.
  </AlertBanner>
);

const defaultFooter = (onClose: () => void) => (
  <PopoverFooter
    leadingButton={
      <Button size="lg" variant="ghost" onClick={onClose}>
        Cancel
      </Button>
    }
  >
    <Button size="lg" variant="solid" onClick={onClose}>
      Action
    </Button>
  </PopoverFooter>
);

// A default dialog: card (desktop) / drawer (mobile), with a footer slot.
const DefaultDemo = ({
  breakpoint,
  error,
  state,
  confirmOnDismiss,
}: {
  breakpoint: DialogBreakpoint;
  error?: boolean;
  state?: DialogState;
  confirmOnDismiss?: boolean;
}) => {
  const [open, setOpen] = useState(false);
  const close = () => setOpen(false);
  return (
    <>
      <Button size="md" variant="solid" onClick={() => setOpen(true)}>
        Open dialog
      </Button>
      <Dialog
        open={open}
        onClose={close}
        title="Title"
        breakpoint={breakpoint}
        errorMessage={error ? errorBanner : undefined}
        state={state}
        onRetry={() => undefined}
        confirmOnDismiss={confirmOnDismiss}
        footer={defaultFooter(close)}
      >
        <SampleBody />
      </Dialog>
    </>
  );
};

// A focus dialog: multi-step, near/full-screen. Manages the current step; the
// footer (Cancel/Back + Next/Create) is generated by Dialog.
const STEP_LABELS = ["Details", "Address", "Review"];

const FocusDemo = ({ breakpoint }: { breakpoint: DialogBreakpoint }) => {
  const [open, setOpen] = useState(false);
  const [step, setStep] = useState(0);
  const count = STEP_LABELS.length;

  const openDialog = () => {
    setStep(0);
    setOpen(true);
  };

  const stepGroup = (
    <StepItemGroup>
      {STEP_LABELS.map((label, i) => {
        const progress: StepItemProgress = i < step ? "completed" : i === step ? "current" : "incompleted";
        return (
          <StepItem
            key={label}
            progress={progress}
            label={label}
            onClick={i < step ? () => setStep(i) : undefined}
          />
        );
      })}
    </StepItemGroup>
  );

  return (
    <>
      <Button size="md" variant="solid" onClick={openDialog}>
        Open focus dialog
      </Button>
      <Dialog
        type="focus"
        open={open}
        onClose={() => setOpen(false)}
        title="Title"
        breakpoint={breakpoint}
        stepGroup={stepGroup}
        currentStep={step}
        stepCount={count}
        onBack={() => setStep((s) => Math.max(0, s - 1))}
        onNext={() => setStep((s) => Math.min(count - 1, s + 1))}
        onFinish={() => setOpen(false)}
        finalActionLabel="Create"
      >
        <SampleBody />
      </Dialog>
    </>
  );
};

/**
 * Dialog — a modal built on Popover. default: a 560px card (desktop) / drawer
 * (mobile). focus: a near/full-screen multi-step flow (always with a StepItemGroup);
 * its footer steps Cancel/Back → Next → the final action.
 */
const meta: Meta<StoryArgs> = {
  title: "Components/Dialog",
  component: Dialog,
  parameters: { layout: "centered" },
  args: { kind: "default", breakpoint: "desktop", error: false },
  argTypes: {
    kind: { options: ["default", "focus"], control: { type: "inline-radio" } },
    breakpoint: { options: ["auto", "desktop", "mobile"], control: { type: "inline-radio" } },
    error: { name: "error message", control: { type: "boolean" }, if: { arg: "kind", eq: "default" } },
  },
};

export default meta;

type Story = StoryObj<StoryArgs>;

export const Playground: Story = {
  render: ({ kind, breakpoint, error }) =>
    kind === "focus" ? <FocusDemo breakpoint={breakpoint} /> : <DefaultDemo breakpoint={breakpoint} error={error} />,
};

/** Default — a 560px centered card. */
export const Default: Story = {
  parameters: { controls: { disable: true } },
  render: () => <DefaultDemo breakpoint="desktop" />,
};

/** Default on mobile — a bottom drawer. */
export const Mobile: Story = {
  parameters: { controls: { disable: true } },
  render: () => <DefaultDemo breakpoint="mobile" />,
};

/** Focus — a near-fullscreen multi-step flow (desktop). Step through Back/Next. */
export const Focus: Story = {
  parameters: { controls: { disable: true } },
  render: () => <FocusDemo breakpoint="desktop" />,
};

// Mock the iOS safe areas (env() is 0 in a desktop browser) so the full-screen
// focus modal shows the status-bar / home-indicator reserves in Storybook.
const withMockSafeArea: Decorator = (Story) => {
  useEffect(() => {
    const el = document.documentElement;
    el.style.setProperty("--dialog-safe-top", "44px");
    el.style.setProperty("--dialog-safe-bottom", "34px");
    return () => {
      el.style.removeProperty("--dialog-safe-top");
      el.style.removeProperty("--dialog-safe-bottom");
    };
  }, []);
  return <Story />;
};

/**
 * Focus on mobile — a full-screen modal (not a drawer). Reserves the iOS safe
 * areas (mocked here at 44px top / 34px bottom).
 */
export const FocusMobile: Story = {
  parameters: { controls: { disable: true } },
  decorators: [withMockSafeArea],
  render: () => <FocusDemo breakpoint="mobile" />,
};

/** Default with an error message pinned above the footer. */
export const WithError: Story = {
  parameters: { controls: { disable: true } },
  render: () => <DefaultDemo breakpoint="desktop" error />,
};

/** Error state — content couldn't be fetched. The body shows an error EmptyState (footer hidden). */
export const ErrorState: Story = {
  parameters: { controls: { disable: true } },
  render: () => <DefaultDemo breakpoint="desktop" state="error" />,
};

/** Offline state — no internet connection. */
export const Offline: Story = {
  parameters: { controls: { disable: true } },
  render: () => <DefaultDemo breakpoint="desktop" state="offline" />,
};

/**
 * Confirm on dismiss — dismissing (scrim / close) shows a warning Prompt on top
 * of the dialog instead of closing. (A focus dialog always does this.)
 */
export const ConfirmDismiss: Story = {
  parameters: { controls: { disable: true } },
  render: () => <DefaultDemo breakpoint="desktop" confirmOnDismiss />,
};
