import React, { useEffect } from "react";

// Global styles loaded for every component:
import "../src/tokens.css"; // design tokens (CSS variables)
import "../src/styles/base.css"; // base behavior fixes (iOS tap highlight)
import "../src/styles/fonts.css"; // Inter + Font Awesome @font-face
import "../src/styles/icons-glyphs.css"; // .g-<name> glyph classes for the Icon
import "../src/styles/icons-glyphs-kit.css"; // .g-<name> classes for the kit (custom) packs
import "../src/styles/storybook-docs.css"; // shared chrome for all docs (.mdx) pages

// Applies the design-system theme by toggling the class the tokens key off of
// (.dark for dark, .light-theme for light) on the document root, and paints the
// canvas with the real app surface token so it follows the theme automatically.
// "auto" SUBSCRIBES to the OS preference — switching the system theme while
// the page is open (e.g. iOS dark mode on a phone) re-applies live.
function ThemeWrapper({ theme, children }) {
  useEffect(() => {
    const html = document.documentElement;
    const apply = (resolved) => {
      html.classList.remove("dark", "dark-theme", "light-theme");
      html.classList.add(resolved === "dark" ? "dark" : "light-theme");
      document.body.style.background = "var(--surface-level-first)";
      document.body.style.color = "var(--text-strong)";
    };

    if (theme !== "auto") {
      apply(theme);
      return undefined;
    }
    const mq = window.matchMedia("(prefers-color-scheme: dark)");
    const onChange = () => apply(mq.matches ? "dark" : "light");
    onChange();
    mq.addEventListener("change", onChange);
    return () => mq.removeEventListener("change", onChange);
  }, [theme]);

  return children;
}

export const globalTypes = {
  theme: {
    description: "Design system theme",
    defaultValue: "auto",
    toolbar: {
      title: "Theme",
      icon: "circlehollow",
      items: [
        { value: "auto", title: "Auto (OS)" },
        { value: "light", title: "Light" },
        { value: "dark", title: "Dark" },
      ],
      dynamicTitle: true,
    },
  },
};

export const decorators = [
  (Story, context) =>
    React.createElement(
      ThemeWrapper,
      { theme: context.globals.theme },
      React.createElement(Story)
    ),
];

/** @type { import('@storybook/react').Preview } */
const preview = {
  parameters: {
    // Background follows the theme (--surface-level-first), so the static
    // backgrounds picker is turned off to avoid a conflicting fixed color.
    backgrounds: { disable: true },
    // Sidebar order: Variables (tokens) first, then Content (the cross-cutting
    // content rules — what text an object row holds, how values are joined,
    // what shows when a value is missing; they belong to no single component,
    // so they get pages of their own under src/content/), then Components —
    // components listed alphabetically A→Z. The Popover family (Popover,
    // PopoverHeader, PopoverFooter, DrawerHeader) is grouped under "Popover". A
    // few groups (Avatar, Badge, Popover) keep a deliberate story order
    // (Playground first).
    options: {
      storySort: {
        method: "alphabetical",
        order: [
          // The demo app goes first — it is the link people open. ONE story:
          // the shell follows the viewport, so there is no Desktop/Mobile split.
          "App",
          "Variables",
          "Content",
          [
            "Object data",
            [
              "Docs",
              "Anatomy",
              "PlaceholderColor",
              "Client",
              "Contact",
              "Equipment",
              "File",
              "Location",
              "TaxRate",
              "Warranty",
              "WorkflowObjects",
            ],
            "Source avatars",
            ["Docs", "Gallery", "Themes", "Sizes", "Tooltip", "InAField"],
            "Text separator",
            [
              "Docs",
              "Anatomy",
              "Pairs",
              "DateWithTime",
              "FileName",
              "AddressParts",
              "Range",
              "SentenceCaption",
              "IncorrectUsage",
              "MissingValues",
              "Wrapping",
            ],
          ],
          "Components",
          [
            "ActivityLog",
            [
              "Docs",
              "Playground",
              "Hero",
              "GroupAccordion",
              "LogStack",
              "StackOfTwo",
              "SingleLog",
              "Symbols",
              "TextWraps",
              "TimestampScale",
              "AccordionClosedAndOpen",
              "EventObjectCreated",
              "EventSingleFieldModified",
              "EventFieldFilledIn",
              "EventSingleFieldCleared",
              "EventBatchModified",
              "ActivityLogGroup",
              "ActivityLogItem",
              "ActivityLogSubItem",
            ],
            "AlertBanner",
            ["Playground", "Types", "Orientations", "Statuses", "Options"],
            "Avatar",
            [
              "Playground",
              "Sizes",
              "Content",
              "Letters",
              "Add-ons",
              "States",
              "AvatarBill",
              "AvatarClient",
              "AvatarCreditNote",
              "AvatarDay",
              "AvatarDiscount",
              "AvatarEquipment",
              "AvatarEstimate",
              "AvatarFile",
              "AvatarInvoice",
              "AvatarJob",
              "AvatarLaborRate",
              "AvatarLive",
              "AvatarLocation",
              "AvatarOther",
              "AvatarPO",
              "AvatarProduct",
              "AvatarRequest",
              "AvatarSeries",
              "AvatarTaxRate",
              "AvatarUser",
              "AvatarVendor",
              "AvatarVisit",
              "AvatarWarning",
              "AvatarWarranty",
            ],
            "AvatarGroup",
            "Badge",
            [
              "Playground",
              "Overview",
              "BadgeColor",
              "BadgeBillStatus",
              "BadgeClientStatus",
              "BadgeCreditNoteStatus",
              "BadgeEstimateStatus",
              "BadgeInvoiceStatus",
              "BadgeJobStatus",
              "BadgePOStatus",
              "BadgePricebookStatus",
              "BadgeRequestStatus",
              "BadgeSeriesStatus",
              "BadgeVendorStatus",
            ],
            "BottomBarNav",
            [
              "BottomBarNav",
              ["Docs", "Playground", "Hero", "Responsiveness", "FixedBottom"],
              "BottomBarNavItem",
              ["Docs", "Playground", "Hero", "States", "Stretched"],
            ],
            "Button",
            [
              "Docs",
              "Playground",
              "Hero",
              "Variants",
              "Sizes",
              "WithIcons",
              "FullWidth",
              "StatesSolid",
              "StatesSubtle",
              "StatesGhost",
              "StatesDanger",
            ],
            "Card",
            [
              "Card",
              [
                "Docs",
                "Playground",
                "Hero",
                "Anatomy",
                "AnatomyHovered",
                "WhenToUse",
                "HoldingListItem",
                "RightSlot",
                "AlertRing",
                "AlertBannerPreview",
                "ErrorState",
                "StateDefault",
                "StateHovered",
                "StatePressed",
                "StateFocused",
                "StateDragging",
                "StateDisabled",
              ],
              "CardFile",
              [
                "Docs",
                "Playground",
                "Hero",
                "AnatomyVideo",
                "AnatomyNoPreview",
                "Responsiveness",
                "Actions",
                "Wrapping",
                "FileTypes",
                "Loading",
              ],
            ],
            "Checkbox",
            [
              "Checkbox",
              ["Docs", "Playground", "Interactive", "Values", "Unchecked", "Indeterminate", "Checked"],
              "CheckboxItem",
              [
                "Docs",
                "Playground",
                "Interactive",
                "Inline",
                "InlineCaption",
                "InlineWrap",
                "InlineIcon",
                "InlineUnchecked",
                "InlineIndeterminate",
                "InlineChecked",
                "InlineLoading",
                "Card",
                "CardNoCaption",
                "CardWrap",
                "CardIcon",
                "CardContainer",
                "CardUnchecked",
                "CardChecked",
                "CardCheckedContainer",
                "CardLoading",
              ],
              "CheckboxGroup",
              ["Docs", "Playground", "Interactive", "Orientation", "Invalid", "InsideInput"],
            ],
            "Chip",
            [
              "Chip",
              [
                "Docs",
                "Playground",
                "Interactive",
                "Sizes",
                "SlotLeftIcon",
                "SlotLeftAvatar",
                "ActiveInactive",
                "InactiveStates",
                "ActiveStates",
                "LoadingSm",
                "LoadingMd",
                "LoadingLg",
              ],
              "ChipGroup",
              ["Docs", "Playground", "Hero", "Sizes", "Wrapping", "FullWidth", "SingleSelect", "MultiSelect"],
            ],
            "Counter",
            ["Playground", "Examples"],
            "DatePicker",
            [
              "DatePicker",
              [
                "Docs",
                "Playground",
                "Desktop",
                "DesktopRange",
                "DesktopWithInput",
                "DesktopRangeWithInput",
                "NoSelection",
                "SixRows",
                "ReturnButton",
                "ReturnTooltip",
                "Mobile",
                "MobileFilled",
                "MobileKeyboard",
                "MobileSwipe",
                "MobileRange",
                "DateFieldTrigger",
                "DateFieldTriggerMobile",
                "ButtonTrigger",
                "ButtonTriggerMobile",
                "RangeDesktop",
                "RangeReturn",
              ],
              "DateChip",
              ["Playground", "Unselected", "UnselectedToday", "Selected", "SelectedToday", "Band"],
            ],
            "Dialog",
            [
              "Playground",
              "Default",
              "Mobile",
              "Focus",
              "FocusMobile",
              "WithError",
              "ErrorState",
              "Offline",
              "ConfirmDismiss",
            ],
            "DisplayModule",
            ["Playground", "Statuses", "Variants", "AccordionStates", "Slots", "Actions", "ErrorState"],
            "Divider",
            ["Docs", "Playground", "Hero", "Orientation", "Contrast", "Dashed", "Padded"],
            "Dropzone",
            ["Docs", "Playground", "Default", "DefaultState", "Hovered", "Pressed", "Focused", "DragOver", "Warning", "RejectionToasts", "Disabled"],
            "EmptyState",
            ["Playground", "Variations", "WithAvatar", "Error"],
            "Fields",
            [
              "DateField",
              ["Playground", "Overview", "InsideInput"],
              "InputGroup",
              [
                "Docs",
                "Playground",
                "DateSelect",
                "DateSelectEmpty",
                "DateSelectEmptyInvalid",
                "DateSelectFilled",
                "DateSelectFilledInvalid",
                "TextSelect",
                "TextSelectEmpty",
                "TextSelectEmptyInvalid",
                "TextSelectFilled",
                "TextSelectFilledInvalid",
                "DateTextSelect",
                "DateTextSelectEmpty",
                "DateTextSelectEmptyInvalid",
                "DateTextSelectFilled",
                "DateTextSelectFilledInvalid",
                "MissingValue",
                "InsideInput",
              ],
              "MediaField",
              ["Docs", "Playground", "TriggerValid", "TriggerInvalid", "Desktop", "Mobile", "Invalid", "InsideInput"],
              "OTPField",
              ["Docs", "Playground", "Basic", "MinMaxWidth", "ActiveByDefault", "ErrorReset", "InputStates", "GroupStates", "MobileKeyboard"],
              "PasswordField",
              [
                "Docs",
                "Playground",
                "Hero",
                "AnatomyDefault",
                "AnatomyNew",
                "AnatomyStrength",
                "AnatomyConfirm",
                "ShowHideButton",
                "StrengthStatuses",
                "PasswordManagerIcon",
                "ConditionProgression",
                "ConditionsLive",
                "DefaultEmptyValid",
                "DefaultEmptyInvalid",
                "DefaultFilledValid",
                "DefaultFilledInvalid",
                "NewEmptyValid",
                "NewEmptyInvalid",
                "NewFilledValid",
                "NewFilledInvalid",
                "ConfirmEmptyValid",
                "ConfirmEmptyInvalid",
                "ConfirmFilledValid",
                "ConfirmFilledInvalid",
                "MobileKeyboard",
                "Variants",
                "States",
                "InsideInput",
              ],
              "SearchField",
              ["Docs", "Playground", "Hero", "AnatomyField", "AnatomyBar", "ClearButton", "FieldStates", "FieldStatesFilled", "BarStates", "BarStatesFilled", "MobileKeyboard", "Field", "Bar"],
              "SelectField",
              [
                "SelectField",
                ["Playground", "States", "MultiSelect", "InsideInput"],
                "SelectFieldBody",
                ["Playground", "Slots"],
              ],
              "TextArea",
              ["Playground", "Overview", "AutoGrow", "InsideInput"],
              "TextField",
              ["Playground", "Overview", "Affixes", "InsideInput"],
            ],
            "FormModule",
            [
              "FormModule",
              ["Playground", "Overview"],
              "FormModuleGroup",
              ["Playground", "ThreeModules"],
            ],
            "GroupLabel",
            ["Playground", "Primary", "Secondary", "PrimaryAccordion", "SecondaryAccordion"],
            "Hint",
            [
              "Hint",
              ["Playground", "States", "TonguePositions", "Content", "Drawer", "WithTrigger"],
              "HintTrigger",
              "HoverHint",
              ["Playground", "Mobile"],
            ],
            "Icon",
            "IconButton",
            [
              "Docs",
              "Playground",
              "Hero",
              "Variants",
              "Sizes",
              "StatesSolid",
              "StatesSubtle",
              "StatesGhost",
              "StatesMuted",
            ],
            "Input",
            [
              "Input",
              ["Playground", "Overview", "Fields", "DerivedMessages"],
              "StrengthIndicator",
              ["Playground", "States", "OnInputLabel"],
            ],
            "InputHelpText",
            ["Playground", "Overview"],
            "ItemGroup",
            ["Docs", "Playground", "DefaultGroup", "SeparatedItems", "WithHeader", "Truncation", "Accordion", "StackedGroups", "Dragging", "Cards"],
            "ItemText",
            [
              "ItemText",
              ["Docs", "Playground", "Overview", "Anatomy", "BlockVariants", "TextPriority", "Alignment", "LineStyles", "LineColors", "SlotPositions", "SlotLeftInstances", "SlotRightInstances", "IconColor", "BadgeRule", "Truncation", "Wrapping", "SlotHug", "Loading", "LoadingPerVariant", "LoadingRightBlock"],
              "ItemValue",
              ["Docs", "Playground", "Anatomy", "Color", "LeftSlot", "LeftSlotIconColor", "InARow", "TitleTruncatesFirst"],
            ],
            "Label",
            ["Playground", "Overview"],
            "LinkButton",
            ["Playground", "Sizes", "ColorSchemes", "WithIcons", "States", "Loading"],
            "ListItem",
            [
              "ListItem",
              [
                "Docs",
                "Playground",
                "Overview",
                "Anatomy",
                "Sizes",
                "CompactControls",
                "LeftSlot",
                "TextVariants",
                "CaptionSlot",
                "Truncation",
                "TruncationTooltip",
                "MultiLine",
                "RightText",
                "RightTextPriority",
                "RightSlots",
                "SlotIcons",
                "SlotButtons",
                "SlotTabGroup",
                "SlotInputs",
                "SlotToggle",
                "SlotAvatars",
                "BottomSlot",
                "BottomButton",
                "BottomTabGroup",
                "BottomInputs",
                "Draggable",
                "DraggingState",
                "InteractiveStates",
                "AccordionStates",
                "AccordionOpenStates",
              ],
              "ListItemSlotIcon",
              ["Playground", "Instances"],
            ],
            "Menu",
            [
              "Menu",
              ["Playground", "Widths", "WithTrigger", "Mobile", "MobileWithTitle", "WithHeader", "MobileWithHeader"],
              "MenuHeader",
              ["Playground", "Overview"],
              "MenuItem",
              ["Docs", "Playground", "Interactive", "Copy", "LeftSlot", "RightSlot", "Overflow", "Toggle", "SubMenu", "States", "Danger", "DangerStates"],
              "MenuItemGroup",
              ["Playground", "Menu"],
            ],
            "Radio",
            [
              "Radio",
              ["Docs", "Playground", "Interactive", "Anatomy", "Unselected", "Selected"],
              "RadioItem",
              [
                "Docs",
                "Playground",
                "Interactive",
                "Inline",
                "InlineCaption",
                "InlineWrap",
                "InlineIcon",
                "InlineUnselected",
                "InlineSelected",
                "InlineLoading",
                "Card",
                "CardNoCaption",
                "CardWrap",
                "CardIcon",
                "CardContainer",
                "CardUnselected",
                "CardSelected",
                "CardSelectedContainer",
                "CardLoading",
              ],
              "RadioGroup",
              ["Docs", "Playground", "Interactive", "Orientation", "Invalid", "InsideInput"],
            ],
            "Popover",
            [
              "DrawerHeader",
              "Popover",
              ["Playground", "Desktop", "Drawer", "Matrix", "Scrollable"],
              "PopoverFooter",
              [
                "Docs",
                "Playground",
                "Hero",
                "Anatomy",
                "SlotLeftKinds",
                "TextWithIcon",
                "Buttons",
                "Layouts",
                "Priority",
                "Truncation",
                "FullWidth",
                "Text",
              ],
              "PopoverHeader",
              ["Playground", "Examples", "Title", "Caption", "Text", "Content", "Body"],
            ],
            "Progress",
            [
              "ProgressBar",
              ["Playground", "Anatomy", "Behavior", "Colors", "Loading"],
              "ProgressRing",
              ["Playground", "Anatomy", "Behavior", "Colors", "Loading"],
            ],
            "Prompt",
            ["Playground", "Desktop", "Mobile", "Danger"],
            "SegmentedControl",
            [
              "Playground",
              "Hero",
              "Anatomy",
              "Segments",
              "FullWidth",
              "Sizes",
              "Content",
              "LeftSlot",
              "Orientation",
              "Selection",
              "Divider",
              "Warning",
              "InactiveStates",
              "Motion",
              "Focus",
            ],
            "SelectList",
            [
              "SelectList",
              ["Playground", "Groups", "Empty", "NoResults", "DialogVariant", "Mobile"],
              "SelectListFooter",
              ["Playground", "MenuItemVariant", "ActionBar"],
              "SelectListHeader",
              ["Playground", "Variants", "Overview"],
              "SelectListItem",
              ["Playground", "Overview", "Object", "Content"],
              "SelectListItemContent",
              ["Playground", "Slots"],
              "SelectListItemCopy",
              ["Playground", "Combinations"],
              "SelectListItemGroup",
              ["Playground", "Groups", "NoLabel"],
            ],
            "SidebarNav",
            [
              "SidebarNav",
              ["Docs", "Playground", "Hero", "Overflow", "Minimal", "LongWorkspaceName"],
              "SidebarNavItem",
              ["Docs", "Playground", "Hero", "Anatomy", "Modifiers", "DefaultItemStates", "StackHeaderStates", "StackItemStates", "Stack"],
              "SidebarNavItemGroup",
              ["Docs", "Playground", "Hero", "Collapsed", "Expanded", "WithActiveItem"],
              "SidebarNavProfileButton",
              ["Docs", "Playground", "Hero", "States", "MenuDesktop", "MenuMobile", "Truncation"],
              "SidebarNavWorkspaceButton",
              ["Docs", "Playground", "Hero", "States", "LongName", "SingleWorkspace", "AvatarFallback", "ListDesktop", "ListMobile"],
            ],
            "SidePanel",
            [
              "SidePanel",
              [
                "Docs",
                "Playground",
                "Hero",
                "Anatomy",
                "HeaderOptions",
                "WithFooter",
                "WithNavigation",
                "MultilevelNavigation",
                "Mobile",
                "NavigationLevels",
                "WarningTabs",
                "WarningTabsTopLevel",
                "WarningInPanel",
                "ErrorState",
                "OfflineState",
              ],
              "SidePanelNavigation",
              ["Playground", "SingleLevel", "MultiLevel", "Overflow"],
            ],
            "Skeleton",
            ["Skeleton", "SkeletonTypography"],
            "StepItemGroup",
            [
              "StepItem",
              ["Docs", "Playground", "Anatomy", "Responsiveness", "Statuses", "Text", "States", "Loading"],
              "StepItemGroup",
              ["Docs", "Playground", "Anatomy", "Quantities", "Overflow", "Interactive"],
            ],
            "Table",
            [
              "CellBody",
              [
                "Docs",
                "Playground",
                "Anatomy",
                "Alignment",
                "SlotRight",
                "LastPinned",
                "Text",
                "ColorSchemes",
                "BadgeContent",
                "AssigneeContent",
                "NumberContent",
                "Empty",
                "Loading",
              ],
              "CellHeader",
              ["Docs", "Playground", "Anatomy", "Truncation", "Alignment", "Pinned", "Sortable", "Sorted", "SortIcons", "Loading"],
              "Table",
              ["Playground", "StickyHeader", "Scrolling", "Loading"],
              "TableRow",
              ["Docs", "Playground", "HeaderRow", "BodyRow", "HeaderInteraction", "Clickable", "Table", "Loading"],
            ],
            "Tabs",
            [
              "TabGroup",
              [
                "Docs",
                "Playground",
                "Hero",
                "Anatomy",
                "Styles",
                "FullWidth",
                "Sizes",
                "Content",
                "LeftSlot",
                "Selection",
                "Warning",
                "Loading",
                "States",
                "Focus",
              ],
            ],
            "Toast",
            [
              "Toast",
              ["Playground", "Overview", "Anatomy", "TextWrap"],
              "Toaster",
              ["Desktop", "Mobile"],
            ],
            "Toggle",
            [
              "Toggle",
              ["Playground", "Interactive", "Anatomy", "Inactive", "Active", "Loading"],
              "ToggleItem",
              ["Playground", "Interactive", "AnatomyCaption", "TextWraps", "Inactive", "Active", "Loading"],
            ],
            "Tooltip",
            "TopBarFilter",
            [
              "FilterChip",
              [
                "Docs",
                "Playground",
                "Hero",
                "ChipContainerDesktop",
                "ChipContainerMobile",
                "ContentBoxPaddings",
                "ContentBoxText",
                "ContentBoxSlot",
                "RemoveBox",
                "IsClickable",
                "InteractionStates",
                "MaxWidth",
                "PropertyBox",
                "ConditionBox",
                "ValueBox",
                "RemoveStates",
                "RemoveTooltip",
                "IsFixed",
                "FixedCondition",
                "FixedValueSingle",
                "FixedValueMultiple",
              ],
              "FilterChipGroup",
              ["Docs", "Playground", "Hero", "AnatomyDesktop", "AnatomyMobile", "AddFilterTooltip", "AddFilterMenu"],
              "TopBarFilter",
              ["Docs", "Playground", "Hero", "StandardView", "FixedFiltersEmpty", "FixedFiltersReset"],
            ],
            "TopBarNav",
            [
              "Docs",
              "Playground",
              "Hero",
              "TabsOptional",
              "BackAndContextMenu",
              "TitleDropdown",
              "TitleStates",
              "TitleAvatar",
              "RightElementsOptional",
              "ListMobile",
              "ListTabsScroll",
              "SubPagesMobile",
              "DetailsDesktop",
              "BackOptional",
              "ContextMenu",
              "ContextMenuMobile",
              "DetailsMobile",
              "HideOnScroll",
              "LiveUsers",
              "LiveUsersMobile",
              "Inner",
            ],
            "TopBarView",
            [
              "Docs",
              "Playground",
              "Hero",
              "AnatomyDesktop",
              "AnatomyMobile",
              "TabsScroll",
              "ViewSelectorOpen",
              "ViewNameTruncation",
              "SearchDesktop",
              "SearchMobile",
              "SearchTooltip",
              "ViewButton",
              "FiltersButton",
              "FiltersButtonStates",
            ],
            "ValueDisplay",
            [
              "ValueDisplay",
              [
                "Docs",
                "Playground",
                // Horizontal
                "Horizontal",
                "HorizontalSlotRight",
                "HorizontalLabelWraps",
                "Text",
                "TextSlotLeft",
                "TextWraps",
                "TextColors",
                "TextEmpty",
                "TextWarning",
                "TextLoading",
                "BadgeValue",
                "BadgeTruncates",
                "BadgeEmpty",
                "BadgeLoading",
                "LinkValue",
                "LinkTruncates",
                "LinkEmpty",
                "LinkLoading",
                // Vertical
                "Vertical",
                "VerticalLabelWraps",
                "ShortText",
                "ShortTextSlotLeft",
                "ShortTextEmpty",
                "ShortTextLoading",
                "LongText",
                "LongTextTruncated",
                "LongTextEmpty",
                "LongTextLoading",
                "AvatarStack",
                "AvatarStackTruncated",
                "AvatarStackNames",
                "AvatarStackEmpty",
                "AvatarStackLoading",
                "Files",
                "FilesOneCard",
                "FilesWrap",
                "FilesEmpty",
                "FilesLoading",
                "ObjectCard",
                "ObjectCardEmpty",
                "ObjectCardLoading",
              ],
              "ValueDisplayGroup",
              ["Playground", "HorizontalOnly", "MultipleVertical", "OrderEnforced"],
            ],
          ],
          "Modules",
          [
            // Grouped into object folders on 2026-09-29 (Daniel). Folders
            // first, A→Z; the two modules that belong to no object yet follow.
            "Equipment",
            [
              '"Equipment" Side Panel',
              [
                "Desktop",
                "Mobile",
                "Warning — missing key details",
                "Warranties",
                "Files",
                "History",
                "History — filtered",
                "Empty",
                "Loading — Details",
                "Loading — Warranties",
                "Notes form — desktop",
                "Notes form — mobile",
                "Error",
              ],
              '"New Equipment" Form',
              ["Desktop", "Mobile"],
            ],
            "File",
            [
              '"Add Files" Form',
              ["Desktop", "Mobile"],
              '"Files" DisplayModule',
              [
                "Desktop",
                "Mobile",
                "Without the view toggle",
                "One group empty",
                "Empty",
                "Approaching the limit",
                "At the limit",
                "Without a limit",
              ],
            ],
            "Job",
            [
              "Job Details",
              [
                '"Job Lifecycle" Module',
                ["Concept 1", "Concept 2", "Concept 3", "Concept 4", "Concept 5"],
                '"Summary" Module',
                [
                  "Empty / Desktop",
                  "Empty / Mobile",
                  "1 Assignee / Desktop",
                  "1 Assignee / Mobile",
                  "5 Assignees / Desktop",
                  "5 Assignees / Mobile",
                ],
                '"Start Job" Form',
                '"Send Summary" Form',
                '"Download PDF" Form',
                ["Parent / Desktop", "Parent / Mobile", "No Parent / Desktop", "No Parent / Mobile"],
              ],
              '"Job Form" Preview',
              ["PanelDesktop", "PanelMobile", "Mapping", "ServiceCall", "HiddenAnswers", "HotSideRepair"],
              '"New Job ∕ Series" Form',
              ["Job", ["Desktop", "Mobile"], "Series", []],
            ],
            "Labor Rate",
            [
              '"New Labor Rate" Form',
              [
                "Desktop",
                "Mobile",
                "One Required Subtype",
                "Required Subtype",
                "No Subtypes",
                "QuickBooks",
                "QuickBooks — No Synced Accounts",
                "Creating",
                "Create Fails",
              ],
              '"Labor Rate" Side Panel',
              [
                "Desktop",
                "Mobile",
                '"Review" Status',
                '"Review" Status Mobile',
                '"Inactive" Status',
                '"General" Module',
                '"Pricing" Module',
                '"Accounting" Module',
                "No QuickBooks Accounting",
                "No Permissions",
                "Loading",
                "Actions Fail",
              ],
            ],
            "Location",
            [
              '"New Location" Form',
              ["Desktop", "Mobile"],
            ],
            "Tax Rate",
            [
              '"New Tax Rate" Form',
              ["Desktop", "Mobile", "No QuickBooks Integration", "Create Fails"],
              '"Tax Rate" Side Panel',
              [
                "Desktop",
                "Mobile",
                '"Review" Status',
                '"Review" Status Mobile',
                '"Inactive" Status',
                '"General" Module',
                '"Accounting" Module',
                "No Accounting Integration",
                "No Permissions",
                "Loading",
                "Actions Fail",
              ],
            ],
            "Warranty",
            [
              '"New Warranty" Form',
              ["Desktop", "Mobile", "Create fails"],
              '"Warranty" Side Panel',
              ["Desktop", "Mobile", "Upcoming", "Expired", "No end date", "Loading", "Actions fail", "Error"],
            ],
            // Not in a folder yet — no object family of their own.
            '"New Service" Form',
            ["Desktop", "Mobile"],
            '"View" Menu',
            ["Docs", "Desktop", "Mobile", "Jobs"],
          ],
          // Filters is the ONLY prototype left: the Job Details page became a
          // shared module on 2026-09-28 (src/modules/JobDetails) and its
          // stories moved to the Modules section with it. Filters goes too,
          // together with its own database copy, when its user test ends.
          "Prototypes",
          [
            "Filters",
            ["Desktop", "Mobile"],
          ],
          // The demo database (src/data/db) — its browser page lives last.
          "Data",
          ["Database"],
        ],
      },
    },
  },
};

export default preview;
