import React, { useEffect } from "react";

// Global styles loaded for every component:
import "../src/tokens.css"; // design tokens (CSS variables)
import "../src/styles/base.css"; // base behavior fixes (iOS tap highlight)
import "../src/styles/fonts.css"; // Inter + Font Awesome @font-face
import "../src/styles/icons-glyphs.css"; // .g-<name> glyph classes for the Icon
import "../src/styles/icons-glyphs-kit.css"; // .g-<name> classes for the kit (custom) packs
import "../src/styles/storybook-docs.css"; // shared chrome for all docs (.mdx) pages

// Applies the design-system theme by toggling the class the tokens key off of
// (.dark for dark, .light-theme for light) on the document root, and paints the
// canvas with the real app surface token so it follows the theme automatically.
// "auto" SUBSCRIBES to the OS preference — switching the system theme while
// the page is open (e.g. iOS dark mode on a phone) re-applies live.
function ThemeWrapper({ theme, children }) {
  useEffect(() => {
    const html = document.documentElement;
    const apply = (resolved) => {
      html.classList.remove("dark", "dark-theme", "light-theme");
      html.classList.add(resolved === "dark" ? "dark" : "light-theme");
      document.body.style.background = "var(--surface-level-first)";
      document.body.style.color = "var(--text-strong)";
    };

    if (theme !== "auto") {
      apply(theme);
      return undefined;
    }
    const mq = window.matchMedia("(prefers-color-scheme: dark)");
    const onChange = () => apply(mq.matches ? "dark" : "light");
    onChange();
    mq.addEventListener("change", onChange);
    return () => mq.removeEventListener("change", onChange);
  }, [theme]);

  return children;
}

export const globalTypes = {
  theme: {
    description: "Design system theme",
    defaultValue: "auto",
    toolbar: {
      title: "Theme",
      icon: "circlehollow",
      items: [
        { value: "auto", title: "Auto (OS)" },
        { value: "light", title: "Light" },
        { value: "dark", title: "Dark" },
      ],
      dynamicTitle: true,
    },
  },
};

export const decorators = [
  (Story, context) =>
    React.createElement(
      ThemeWrapper,
      { theme: context.globals.theme },
      React.createElement(Story)
    ),
];

/** @type { import('@storybook/react').Preview } */
const preview = {
  parameters: {
    // Background follows the theme (--surface-level-first), so the static
    // backgrounds picker is turned off to avoid a conflicting fixed color.
    backgrounds: { disable: true },
    // Sidebar order: Variables (tokens) first, then Components — components
    // listed alphabetically A→Z. The Popover family (Popover, PopoverHeader,
    // PopoverFooter, DrawerHeader) is grouped under "Popover". A few groups
    // (Avatar, Badge, Popover) keep a deliberate story order (Playground first).
    options: {
      storySort: {
        method: "alphabetical",
        order: [
          "Variables",
          "Components",
          [
            "ActivityLog",
            [
              "Docs",
              "Playground",
              "Hero",
              "GroupAccordion",
              "LogStack",
              "StackOfTwo",
              "SingleLog",
              "Symbols",
              "TextWraps",
              "TimestampScale",
              "AccordionClosedAndOpen",
              "EventObjectCreated",
              "EventSingleFieldModified",
              "EventFieldFilledIn",
              "EventSingleFieldCleared",
              "EventBatchModified",
              "ActivityLogGroup",
              "ActivityLogItem",
              "ActivityLogSubItem",
            ],
            "AlertBanner",
            ["Playground", "Types", "Orientations", "Statuses", "Options"],
            "Avatar",
            [
              "Playground",
              "Sizes",
              "Content",
              "Letters",
              "Add-ons",
              "States",
              "AvatarBill",
              "AvatarClient",
              "AvatarCreditNote",
              "AvatarDay",
              "AvatarDiscount",
              "AvatarEquipment",
              "AvatarEstimate",
              "AvatarFile",
              "AvatarInvoice",
              "AvatarJob",
              "AvatarJobRequest",
              "AvatarJobSeries",
              "AvatarLabor",
              "AvatarLive",
              "AvatarLocation",
              "AvatarOther",
              "AvatarPO",
              "AvatarProduct",
              "AvatarTaxRate",
              "AvatarUser",
              "AvatarVendor",
              "AvatarVisit",
              "AvatarWarning",
              "AvatarWarranty",
            ],
            "AvatarGroup",
            "Badge",
            [
              "Playground",
              "Overview",
              "BadgeColor",
              "BadgeBillStatus",
              "BadgeClientStatus",
              "BadgeCreditNoteStatus",
              "BadgeEstimateStatus",
              "BadgeInvoiceStatus",
              "BadgeJobStatus",
              "BadgeJobRequestStatus",
              "BadgeJobSeriesStatus",
              "BadgePOStatus",
              "BadgePricebookStatus",
              "BadgeVendorStatus",
            ],
            "BottomBarNav",
            [
              "BottomBarNav",
              ["Docs", "Playground", "Hero", "Responsiveness", "FixedBottom"],
              "BottomBarNavItem",
              ["Docs", "Playground", "Hero", "States", "Stretched"],
            ],
            "Button",
            [
              "Docs",
              "Playground",
              "Hero",
              "Variants",
              "Sizes",
              "WithIcons",
              "FullWidth",
              "StatesSolid",
              "StatesSubtle",
              "StatesGhost",
              "StatesDanger",
            ],
            "Card",
            [
              "Card",
              [
                "Docs",
                "Playground",
                "Hero",
                "AnatomyRing",
                "AnatomyBanner",
                "ErrorState",
                "StateDefault",
                "StateFocused",
                "StateHovered",
                "StatePressed",
                "StateDragging",
                "StateDisabled",
                "StateLoading",
              ],
              "CardFile",
              [
                "Docs",
                "Playground",
                "Hero",
                "AnatomyVideo",
                "AnatomyNoPreview",
                "Responsiveness",
                "Actions",
                "Wrapping",
                "FileTypes",
                "Loading",
              ],
            ],
            "Checkbox",
            [
              "Checkbox",
              ["Docs", "Playground", "Interactive", "Values", "Unchecked", "Indeterminate", "Checked"],
              "CheckboxItem",
              [
                "Docs",
                "Playground",
                "Interactive",
                "Inline",
                "InlineCaption",
                "InlineWrap",
                "InlineIcon",
                "InlineUnchecked",
                "InlineIndeterminate",
                "InlineChecked",
                "InlineLoading",
                "Card",
                "CardNoCaption",
                "CardWrap",
                "CardIcon",
                "CardContainer",
                "CardUnchecked",
                "CardChecked",
                "CardCheckedContainer",
                "CardLoading",
              ],
              "CheckboxGroup",
              ["Docs", "Playground", "Interactive", "Orientation", "Invalid", "InsideInput"],
            ],
            "Chip",
            [
              "Chip",
              [
                "Docs",
                "Playground",
                "Interactive",
                "Sizes",
                "SlotLeftIcon",
                "SlotLeftAvatar",
                "ActiveInactive",
                "InactiveStates",
                "ActiveStates",
                "LoadingSm",
                "LoadingMd",
                "LoadingLg",
              ],
              "ChipGroup",
              ["Docs", "Playground", "Hero", "Sizes", "Wrapping", "FullWidth", "SingleSelect", "MultiSelect"],
            ],
            "Counter",
            ["Playground", "Examples"],
            "DatePicker",
            [
              "DatePicker",
              [
                "Docs",
                "Playground",
                "Desktop",
                "DesktopRange",
                "DesktopWithInput",
                "DesktopRangeWithInput",
                "NoSelection",
                "SixRows",
                "ReturnButton",
                "ReturnTooltip",
                "Mobile",
                "MobileFilled",
                "MobileKeyboard",
                "MobileSwipe",
                "MobileRange",
                "DateFieldTrigger",
                "DateFieldTriggerMobile",
                "ButtonTrigger",
                "ButtonTriggerMobile",
                "RangeDesktop",
                "RangeReturn",
              ],
              "DateChip",
              ["Playground", "Unselected", "UnselectedToday", "Selected", "SelectedToday", "Band"],
            ],
            "Dialog",
            [
              "Playground",
              "Default",
              "Mobile",
              "Focus",
              "FocusMobile",
              "WithError",
              "ErrorState",
              "Offline",
              "ConfirmDismiss",
            ],
            "DisplayModule",
            ["Playground", "Statuses", "Variants", "AccordionStates", "Slots", "Actions", "ErrorState"],
            "Divider",
            ["Docs", "Playground", "Hero", "Orientation", "Contrast", "Dashed", "Padded"],
            "Dropzone",
            ["Docs", "Playground", "Default", "DefaultState", "Hovered", "Pressed", "Focused", "DragOver", "Warning", "RejectionToasts", "Disabled"],
            "EmptyState",
            ["Playground", "Variations", "WithAvatar", "Error"],
            "Fields",
            [
              "DateField",
              ["Playground", "Overview", "InsideInput"],
              "InputGroup",
              [
                "Docs",
                "Playground",
                "DateSelect",
                "DateSelectEmpty",
                "DateSelectEmptyInvalid",
                "DateSelectFilled",
                "DateSelectFilledInvalid",
                "TextSelect",
                "TextSelectEmpty",
                "TextSelectEmptyInvalid",
                "TextSelectFilled",
                "TextSelectFilledInvalid",
                "DateTextSelect",
                "DateTextSelectEmpty",
                "DateTextSelectEmptyInvalid",
                "DateTextSelectFilled",
                "DateTextSelectFilledInvalid",
                "MissingValue",
                "InsideInput",
              ],
              "MediaField",
              ["Docs", "Playground", "TriggerValid", "TriggerInvalid", "Desktop", "Mobile", "Invalid", "InsideInput"],
              "OTPField",
              ["Docs", "Playground", "Basic", "MinMaxWidth", "ActiveByDefault", "ErrorReset", "InputStates", "GroupStates", "MobileKeyboard"],
              "PasswordField",
              [
                "Docs",
                "Playground",
                "Hero",
                "AnatomyDefault",
                "AnatomyNew",
                "AnatomyStrength",
                "AnatomyConfirm",
                "ShowHideButton",
                "StrengthStatuses",
                "PasswordManagerIcon",
                "ConditionProgression",
                "ConditionsLive",
                "DefaultEmptyValid",
                "DefaultEmptyInvalid",
                "DefaultFilledValid",
                "DefaultFilledInvalid",
                "NewEmptyValid",
                "NewEmptyInvalid",
                "NewFilledValid",
                "NewFilledInvalid",
                "ConfirmEmptyValid",
                "ConfirmEmptyInvalid",
                "ConfirmFilledValid",
                "ConfirmFilledInvalid",
                "MobileKeyboard",
                "Variants",
                "States",
                "InsideInput",
              ],
              "SearchField",
              ["Docs", "Playground", "Hero", "AnatomyField", "AnatomyBar", "ClearButton", "FieldStates", "FieldStatesFilled", "BarStates", "BarStatesFilled", "MobileKeyboard", "Field", "Bar"],
              "SelectField",
              [
                "SelectField",
                ["Playground", "States", "MultiSelect", "InsideInput"],
                "SelectFieldBody",
                ["Playground", "Slots"],
              ],
              "TextArea",
              ["Playground", "Overview", "AutoGrow", "InsideInput"],
              "TextField",
              ["Playground", "Overview", "Affixes", "InsideInput"],
            ],
            "FormModule",
            [
              "FormModule",
              ["Playground", "Overview"],
              "FormModuleGroup",
              ["Playground", "ThreeModules"],
            ],
            "GroupLabel",
            ["Playground", "Primary", "Secondary", "PrimaryAccordion", "SecondaryAccordion"],
            "Hint",
            [
              "Hint",
              ["Playground", "States", "TonguePositions", "Content", "Drawer", "WithTrigger"],
              "HintTrigger",
              "HoverHint",
              ["Playground", "Mobile"],
            ],
            "Icon",
            "IconButton",
            [
              "Docs",
              "Playground",
              "Hero",
              "Variants",
              "Sizes",
              "StatesSolid",
              "StatesSubtle",
              "StatesGhost",
              "StatesMuted",
            ],
            "Input",
            [
              "Input",
              ["Playground", "Overview", "Fields", "DerivedMessages"],
              "StrengthIndicator",
              ["Playground", "States", "OnInputLabel"],
            ],
            "InputHelpText",
            ["Playground", "Overview"],
            "ItemGroup",
            ["Docs", "Playground", "DefaultGroup", "SeparatedItems", "WithHeader", "Truncation", "Accordion", "StackedGroups", "Dragging", "Cards"],
            "Label",
            ["Playground", "Overview"],
            "LinkButton",
            ["Playground", "Sizes", "ColorSchemes", "WithIcons", "States", "Loading"],
            "ListItem",
            [
              "ListItem",
              [
                "Docs",
                "Playground",
                "Overview",
                "Anatomy",
                "LeftSlot",
                "TextVariants",
                "CaptionSlot",
                "Truncation",
                "TruncationTooltip",
                "MultiLine",
                "RightText",
                "RightTextPriority",
                "RightSlots",
                "SlotIcons",
                "SlotButtons",
                "SlotTabGroup",
                "SlotInputs",
                "SlotToggle",
                "SlotAvatars",
                "BottomSlot",
                "BottomButton",
                "BottomTabGroup",
                "BottomInputs",
                "Draggable",
                "DraggingState",
                "InteractiveStates",
                "AccordionStates",
                "AccordionOpenStates",
              ],
              "ListItemBody",
              ["Playground", "Instances", "MultipleInstances"],
              "ListItemContent",
              ["Playground", "Combinations"],
              "ListItemSlotIcon",
              ["Playground", "Instances"],
              "ListItemText",
              ["Playground", "Combinations"],
              "ListItemTextLeft",
              ["Playground", "Variants", "TruncationRules"],
              "ListItemTextRight",
              ["Playground", "Variants"],
            ],
            "Menu",
            [
              "Menu",
              ["Playground", "Widths", "WithTrigger", "Mobile", "MobileWithTitle", "WithHeader", "MobileWithHeader"],
              "MenuHeader",
              ["Playground", "Overview"],
              "MenuItem",
              ["Docs", "Playground", "Interactive", "Copy", "LeftSlot", "RightSlot", "Overflow", "Toggle", "SubMenu", "States", "Danger", "DangerStates"],
              "MenuItemGroup",
              ["Playground", "Menu"],
            ],
            "Radio",
            [
              "Radio",
              ["Docs", "Playground", "Interactive", "Anatomy", "Unselected", "Selected"],
              "RadioItem",
              [
                "Docs",
                "Playground",
                "Interactive",
                "Inline",
                "InlineCaption",
                "InlineWrap",
                "InlineIcon",
                "InlineUnselected",
                "InlineSelected",
                "InlineLoading",
                "Card",
                "CardNoCaption",
                "CardWrap",
                "CardIcon",
                "CardContainer",
                "CardUnselected",
                "CardSelected",
                "CardSelectedContainer",
                "CardLoading",
              ],
              "RadioGroup",
              ["Docs", "Playground", "Interactive", "Orientation", "Invalid", "InsideInput"],
            ],
            "Popover",
            [
              "DrawerHeader",
              "Popover",
              ["Playground", "Desktop", "Drawer", "Matrix", "Scrollable"],
              "PopoverFooter",
              [
                "Docs",
                "Playground",
                "Hero",
                "Anatomy",
                "SlotLeftKinds",
                "TextWithIcon",
                "Buttons",
                "Layouts",
                "Priority",
                "Truncation",
                "FullWidth",
                "Text",
              ],
              "PopoverHeader",
              ["Playground", "Examples", "Title", "Caption", "Text", "Content", "Body"],
            ],
            "Progress",
            [
              "ProgressBar",
              ["Playground", "Anatomy", "Behavior", "Colors", "Loading"],
              "ProgressRing",
              ["Playground", "Anatomy", "Behavior", "Colors", "Loading"],
            ],
            "Prompt",
            ["Playground", "Desktop", "Mobile", "Danger"],
            "SelectList",
            [
              "SelectList",
              ["Playground", "Groups", "Empty", "NoResults", "DialogVariant", "Mobile"],
              "SelectListFooter",
              ["Playground", "MenuItemVariant", "ActionBar"],
              "SelectListHeader",
              ["Playground", "Variants", "Overview"],
              "SelectListItem",
              ["Playground", "Overview", "Object", "Content"],
              "SelectListItemContent",
              ["Playground", "Slots"],
              "SelectListItemCopy",
              ["Playground", "Combinations"],
              "SelectListItemGroup",
              ["Playground", "Groups", "NoLabel"],
            ],
            "SidebarNav",
            [
              "SidebarNav",
              ["Docs", "Playground", "Hero", "Overflow", "Minimal", "LongWorkspaceName"],
              "SidebarNavItem",
              ["Docs", "Playground", "Hero", "Anatomy", "Modifiers", "DefaultItemStates", "StackHeaderStates", "StackItemStates", "Stack"],
              "SidebarNavItemGroup",
              ["Docs", "Playground", "Hero", "Collapsed", "Expanded", "WithActiveItem"],
              "SidebarNavProfileButton",
              ["Docs", "Playground", "Hero", "States", "MenuDesktop", "MenuMobile", "Truncation"],
              "SidebarNavWorkspaceButton",
              ["Docs", "Playground", "Hero", "States", "LongName", "SingleWorkspace", "AvatarFallback", "ListDesktop", "ListMobile"],
            ],
            "SidePanel",
            [
              "SidePanel",
              [
                "Docs",
                "Playground",
                "Hero",
                "Anatomy",
                "HeaderOptions",
                "WithFooter",
                "WithNavigation",
                "MultilevelNavigation",
                "Mobile",
                "NavigationLevels",
                "WarningTabs",
                "WarningTabsTopLevel",
                "WarningInPanel",
                "ErrorState",
                "OfflineState",
              ],
              "SidePanelNavigation",
              ["Playground", "SingleLevel", "MultiLevel", "Overflow"],
            ],
            "Skeleton",
            ["Skeleton", "SkeletonTypography"],
            "StepItemGroup",
            [
              "StepItem",
              ["Docs", "Playground", "Anatomy", "Responsiveness", "Statuses", "Text", "States", "Loading"],
              "StepItemGroup",
              ["Docs", "Playground", "Anatomy", "Quantities", "Overflow", "Interactive"],
            ],
            "Table",
            [
              "CellBody",
              [
                "Docs",
                "Playground",
                "Anatomy",
                "Alignment",
                "SlotRight",
                "LastPinned",
                "Text",
                "ColorSchemes",
                "BadgeContent",
                "AssigneeContent",
                "NumberContent",
                "Empty",
                "Loading",
              ],
              "CellHeader",
              ["Docs", "Playground", "Anatomy", "Truncation", "Alignment", "Pinned", "Sortable", "Sorted", "SortIcons", "Loading"],
              "Table",
              ["Playground", "StickyHeader", "Scrolling", "Loading"],
              "TableRow",
              ["Docs", "Playground", "HeaderRow", "BodyRow", "HeaderInteraction", "Clickable", "Table", "Loading"],
            ],
            "Tabs",
            [
              "TabGroup",
              [
                "Docs",
                "Playground",
                "GroupDefault",
                "DefaultSmall",
                "DefaultMedium",
                "DefaultLarge",
                "DefaultIcon",
                "DefaultAvatar",
                "DefaultCounter",
                "DefaultIconOnly",
                "DefaultIconOnlyCounter",
                "DefaultStatesInactive",
                "DefaultStatesActive",
                "GroupContained",
                "ContainedSmall",
                "ContainedMedium",
                "ContainedLarge",
                "ContainedIcon",
                "ContainedAvatar",
                "ContainedCounter",
                "ContainedIconOnly",
                "ContainedIconOnlyCounter",
                "ContainedVertical",
                "ContainedStatesInactive",
                "ContainedStatesActive",
                "GroupUnderlined",
                "UnderlinedSmall",
                "UnderlinedMedium",
                "UnderlinedIcon",
                "UnderlinedAvatar",
                "UnderlinedCounter",
                "UnderlinedIconOnly",
                "UnderlinedIconOnlyCounter",
                "UnderlinedStatesInactive",
                "UnderlinedStatesActive",
              ],
              "TabItem",
              ["Playground", "Default", "Container", "Underline", "Vertical", "Sizes", "Content", "Avatar"],
            ],
            "Toast",
            [
              "Toast",
              ["Playground", "Overview", "Anatomy", "TextWrap"],
              "Toaster",
              ["Desktop", "Mobile"],
            ],
            "Toggle",
            [
              "Toggle",
              ["Playground", "Interactive", "Anatomy", "Inactive", "Active", "Loading"],
              "ToggleItem",
              ["Playground", "Interactive", "AnatomyCaption", "TextWraps", "Inactive", "Active", "Loading"],
            ],
            "Tooltip",
            "TopBarFilter",
            [
              "FilterChip",
              [
                "Docs",
                "Playground",
                "Hero",
                "ChipContainerDesktop",
                "ChipContainerMobile",
                "ContentBoxPaddings",
                "ContentBoxText",
                "ContentBoxSlot",
                "RemoveBox",
                "IsClickable",
                "InteractionStates",
                "MaxWidth",
                "PropertyBox",
                "ConditionBox",
                "ValueBox",
                "RemoveStates",
                "RemoveTooltip",
                "IsFixed",
                "FixedCondition",
                "FixedValueSingle",
                "FixedValueMultiple",
              ],
              "FilterChipGroup",
              ["Docs", "Playground", "Hero", "AnatomyDesktop", "AnatomyMobile", "AddFilterTooltip", "AddFilterMenu"],
              "TopBarFilter",
              ["Docs", "Playground", "Hero", "StandardView", "FixedFiltersEmpty", "FixedFiltersReset"],
            ],
            "TopBarNav",
            [
              "Docs",
              "Playground",
              "Hero",
              "TabsOptional",
              "BackAndContextMenu",
              "TitleDropdown",
              "TitleStates",
              "TitleAvatar",
              "RightElementsOptional",
              "ListMobile",
              "ListTabsScroll",
              "SubPagesMobile",
              "DetailsDesktop",
              "BackOptional",
              "ContextMenu",
              "ContextMenuMobile",
              "DetailsMobile",
              "HideOnScroll",
              "LiveUsers",
              "LiveUsersMobile",
              "Inner",
            ],
            "TopBarView",
            [
              "Docs",
              "Playground",
              "Hero",
              "AnatomyDesktop",
              "AnatomyMobile",
              "TabsScroll",
              "ViewSelectorOpen",
              "ViewNameTruncation",
              "SearchDesktop",
              "SearchMobile",
              "SearchTooltip",
              "ViewButton",
              "FiltersButton",
              "FiltersButtonStates",
            ],
            "ValueDisplay",
            [
              "ValueDisplay",
              [
                "Docs",
                "Playground",
                // Horizontal
                "Horizontal",
                "HorizontalSlotRight",
                "HorizontalLabelWraps",
                "Text",
                "TextSlotLeft",
                "TextTruncates",
                "TextColors",
                "TextEmpty",
                "TextWarning",
                "TextLoading",
                "BadgeValue",
                "BadgeTruncates",
                "BadgeEmpty",
                "BadgeLoading",
                "LinkValue",
                "LinkTruncates",
                "LinkEmpty",
                "LinkLoading",
                // Vertical
                "Vertical",
                "VerticalLabelWraps",
                "ShortText",
                "ShortTextSlotLeft",
                "ShortTextEmpty",
                "ShortTextLoading",
                "LongText",
                "LongTextTruncated",
                "LongTextEmpty",
                "LongTextLoading",
                "AvatarStack",
                "AvatarStackTruncated",
                "AvatarStackNames",
                "AvatarStackEmpty",
                "AvatarStackLoading",
                "Files",
                "FilesOneCard",
                "FilesWrap",
                "FilesEmpty",
                "FilesLoading",
                "ObjectCard",
                "ObjectCardEmpty",
                "ObjectCardLoading",
              ],
              "ValueDisplayGroup",
              ["Playground", "HorizontalOnly", "MultipleVertical", "OrderEnforced"],
            ],
          ],
          "Modules",
          [
            '"Add Files" Form',
            ["Desktop", "Mobile"],
            '"Job Form" Preview',
            ["PanelDesktop", "PanelMobile", "Mapping", "ServiceCall", "HiddenAnswers", "HotSideRepair"],
            '"New Equipment" Form',
            ["Desktop", "Mobile"],
            '"New Job ∕ Series" Form',
            ["Job", ["Desktop", "Mobile"], "Series", []],
            '"New Location" Form',
            ["Desktop", "Mobile"],
            '"New Service" Form',
            ["Desktop", "Mobile"],
            '"View" Menu',
            ["Docs", "Desktop", "Mobile", "Jobs"],
          ],
          "Prototypes",
          [
            "Filters",
            ["Desktop", "Mobile"],
            "Job Details",
            [
              "Desktop",
              "Mobile",
              '"Job Lifecycle" Module',
              ["Concept 1", "Concept 2", "Concept 3", "Concept 4", "Concept 5"],
              '"Summary" Module',
              [
                "Empty / Desktop",
                "Empty / Mobile",
                "1 Assignee / Desktop",
                "1 Assignee / Mobile",
                "5 Assignees / Desktop",
                "5 Assignees / Mobile",
              ],
              '"Send Summary" Form',
              '"Download PDF" Form',
              ["Parent / Desktop", "Parent / Mobile", "No Parent / Desktop", "No Parent / Mobile"],
            ],
            "Time Tracker",
            [
              "Concept 3",
              "Concept 4",
              "Concept 5",
              "Concept 6",
              ["Desktop", "Mobile", "MobileFullscreen"],
              "Concept 7",
              ["Desktop", "Mobile", "MobileFullscreen"],
              "Concept 8",
              ["Tech / Desktop", "Tech / Mobile", "Office / Desktop"],
            ],
          ],
          // The demo database (src/data/db) — its browser page lives last.
          "Data",
          ["Database"],
        ],
      },
    },
  },
};

export default preview;
