// Demo data for the New-equipment form.
//
// Categories and types are the REAL product lists — read out of the production
// app's `EquipmentCategories` / `EquipmentTypes` choices
// (roopairs_api/roopairs/apps/core/models.py, read-only reference). Categories
// keep their product order; every type belongs to one category, so the Type
// list follows the chosen Category.

export const EQUIPMENT_CATEGORIES: string[] = [
  "Cooking Equipment",
  "Fryers",
  "Ice Machines",
  "Ovens and Ranges",
  "Concession and Condiment Equipment",
  "Dishwashing Equipment",
  "Holding and Warming Equipment",
  "Refrigeration",
  "Beverage Equipment",
  "Food Preparation Equipment",
  "Laundry",
  "Plumbing",
  "Air Purifiers",
  "Worktable, Shelf, and Transport Cart",
  "HVAC",
  "Water Filtration",
  "Lighting and Electrical",
  "Other",
];

/** The types of each category — the Type list is filtered by the chosen Category. */
export const EQUIPMENT_TYPES: Record<string, string[]> = {
  "Cooking Equipment": [
    "Broiler",
    "Charbroiler",
    "Commercial Microwave",
    "Commercial Toaster",
    "Food Rethermalizer and Bain-Marie Heater",
    "Grill and Griddle",
    "Kettle, Skillet, and Pan",
    "Pasta Cooker",
    "Non-Commercial Microwave",
    "Rice Cooker",
    "Salamander and Cheesemelter",
    "Specialty Cooking Equipment",
    "Panini Press",
  ],
  "Fryers": [
    "Electric Fryer",
    "Fryer Filtration Equipment",
    "Gas Fryer",
  ],
  "Ice Machines": [
    "Ice Bin",
    "Ice Dispenser",
    "Ice Maker",
    "Ice Merchandiser",
  ],
  "Ovens and Ranges": [
    "Combi Oven",
    "Convection Oven",
    "Countertop Electric Range",
    "Countertop Gas Range",
    "Electric Oven",
    "Electric Range",
    "Gas Oven",
    "Gas Range",
    "Rotisserie Oven",
    "Smoker",
    "Steamer",
    "Rack and Rotary Oven",
    "Conveyor Oven",
    "Speed Oven",
  ],
  "Concession and Condiment Equipment": [
    "Cheese Warmer",
    "Condiment Holder",
    "Condiment Pump",
    "Cotton Candy Machine",
    "Dessert Equipment",
    "Nacho Station",
    "Napkin Dispenser",
    "Popcorn Machine",
  ],
  "Dishwashing Equipment": [
    "Burnisher",
    "Dishtable",
    "Dishwasher",
    "Garbage Disposer",
    "Glass Washer",
    "Powersoak Sink",
    "Tray Conveyor",
  ],
  "Holding and Warming Equipment": [
    "Bun Warmer",
    "Dish and Tray Dispenser",
    "Display Cabinet",
    "Drawer Warmer",
    "Fried Food Holding Station",
    "Heat Lamp and Carving Station",
    "Heated Merchandiser and Display Cabinet",
    "Heated Shelf",
    "Hot and Cold Food Well",
    "Hot Dog Roller",
    "Hot Dog Steamer",
    "Overhead Food Warmer",
    "Proofing Cabinet",
    "Soup Warmer and Kettle",
    "Soup Well",
    "Warming Cabinet",
    "Steam Table",
    "Steam Well",
  ],
  "Refrigeration": [
    "Bar Refrigeration",
    "Blast Chiller",
    "Chef Base Freezer",
    "Chef Base Refrigerator",
    "Combination Refrigerator and Freezer",
    "Condensing Unit",
    "Ice Cream Equipment",
    "Prep Table",
    "Reach-In Freezer",
    "Reach-In Refrigerator",
    "Refrigerated Merchandiser",
    "Undercounter Freezer",
    "Undercounter Refrigerator",
    "Walk-In Cooler",
    "Walk-In Freezer",
  ],
  "Beverage Equipment": [
    "Bar Blender",
    "Coffee Grinder",
    "Coffee Maker",
    "Coffee Urn",
    "Frozen Drink Machine",
    "Hot Chocolate Machine",
    "Hot Water Dispenser",
    "Juice and Cold Beverage Dispenser",
    "Liquor and Beer Dispenser",
    "Milk and Cream Dispenser",
    "Milkshake Machine",
    "Soft Drink Beverage Dispenser",
    "Tea Brewer",
    "Tea Dispenser",
    "Espresso Machine",
    "Iced Coffee Brewer",
  ],
  "Food Preparation Equipment": [
    "Blender",
    "Commercial Can Openers",
    "Dicer, Cutter, and Chopper",
    "Dough Roller, Press, and Sheeter",
    "Food Packaging",
    "Food Processor",
    "Juicer",
    "Meat Grinder",
    "Meat Press and Pusher",
    "Mixer",
    "Peeler, Corer, and Wedger",
    "Salad Dryer and Spinner",
    "Slicer",
    "Timer and Scale",
  ],
  "Laundry": [
    "Dryer",
    "Washer Dryer Combo",
    "Washer",
  ],
  "Plumbing": [
    "Faucet and Nozzle",
    "Hand Dryer",
    "Hands-Free Faucet",
    "Sink and Drain",
    "Water Heater",
    "Grease Trap",
  ],
  "Air Purifiers": [
    "Commercial Air Purifier",
    "Home Air Purifier",
  ],
  "Worktable, Shelf, and Transport Cart": [
    "Cart, Truck, and Dolly",
    "Rack and Shelf",
    "Worktable and Station",
  ],
  "HVAC": [
    "Condenser",
    "Furnace",
    "Chiller",
    "Air Handler",
    "VRF",
    "Mini Split",
    "Makeup Air Unit (MAU)",
    "Exhaust Fan",
    "Fly Fan and Air Curtain",
    "Portable Unit",
    "Package Unit",
    "Thermostat",
    "Boiler",
    "Dehumidifier",
  ],
  "Water Filtration": [
    "Water Filter",
  ],
  "Lighting and Electrical": [
    "Lighting",
    "Electrical",
  ],
  "Other": [],
};

/** Ownership options (Figma 23960-15937 — the same values as the product's
 *  `EquipmentOwnershipTypes`). */
export const OWNERSHIP_TYPES: string[] = ["Unknown", "Owned", "Leased", "Rented"];

/** The label pool — the Figma "Equipment labels" select list values
 *  (23849-7052). */
export const LABEL_POOL: string[] = [
  "Complicated",
  "Easy to maintain",
  "Hard to install",
  "Kitchen",
  "Contracted",
  "Inactive",
  "Pending onboarding",
  "Premium",
  "Suspended",
  "Standard",
  "Third-party billing",
  "Trial",
  "Walk-in / One-time",
  "Warranty-covered",
];
